modules/document/models/Categories.php
<?php
/**
 * Categories.php
 * Created By
 * feri_
 * 23/01/2023
 */

namespace app\modules\document\models;

use app\component\DataTableAjax;
use yii\bootstrap5\Html;
use yii\helpers\Json;
use yii\helpers\Url;
use app\modelsDB\Users;
use yii\helpers\ArrayHelper;
use Yii;

/**
 *
 * @property-read void $userCreate
 * @property-read string $actions
 * @property-read string $categoryName
 * @property-read string $doc
 * @property-read \yii\db\ActiveQuery $document
 * @property-read void $nama
 */
class Categories extends \app\modelsDB\TblCategoryDocument
{

    public function rules()
    {
        return [
            [['description'], 'required'],
            [['type','level'], 'integer'],
            [['description'], 'string', 'max' => 200],
            [['user_id'], 'string', 'max' => 100],
            [['userArray'],'safe'],
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     *
     */
    public function getDocument(){
        return $this->hasMany(Documents::className(),['category_id'=>'id']);
    }

    /**
     * @return string
     */
    public function getActions(){

        if(Yii::$app->user->identity->level==2){
            $out=Html::tag('div',
            Html::tag('div',
                Html::tag('a','<i class="bx bx-pen"></i>',['href'=>Url::to(['/document/default/edit','id'=>$this->id,'jenis'=>$this->getReq($this->type)]),'class'=>'btn btn-sm btn-outline-primary','title'=>'edit jenis dokumen',]).
                Html::tag('a','<i class="bx bx-trash-alt"></i>',['href'=>Url::toRoute(['/document/default/delete','id'=>$this->id,'title'=>'delete jenis dokumen']),'class'=>'btn btn-sm btn-outline-danger','data-action'=>'delete']).
                Html::tag('a','<i class="bx bx-show"></i>',['href'=>Url::toRoute(['/document/default/view','id'=>$this->id,'jenis'=>$this->getReq($this->type)]),'class'=>'btn btn-sm btn-outline-secondary','title'=>'view file dokumen'])
                ,['class'=>'btn-group']),
            ['class'=>'col']);
            return $out;
        }
        return  Html::tag('div',
            Html::tag('div',
             Html::tag('a','<i class="bx bx-show"></i>',['href'=>Url::toRoute(['/document/default/view','id'=>$this->id,'jenis'=>$this->getReq($this->type)]),'class'=>'btn btn-sm btn-outline-secondary','title'=>'view file dokumen'])
                ,['class'=>'btn-group']),
            ['class'=>'col']);
    }

    public function getDetail(){
        return '';
    }
    public function renderData($params){
        $q=self::find();
        $type=1;
        if(isset($params['jenis'])&& $params['jenis']!=''){
            if($params['jenis']=='ISO 17065'){
                $type=1;
            }
            if($params['jenis']=='internal'){
                $type=3;
            }
            if($params['jenis']=='eksternal'){
                $type=2;
            }
        }
        if(isset($params['jenis'])){
            $q->andFilterWhere(['type'=>$type]);
        }
        if(Yii::$app->user->identity->level!=2){
            $q->andFilterWhere(['like','user_id',Yii::$app->user->identity->id_user]);
        }
        $total=$q->count('id');
        if (isset($params['columns'])){
            foreach ($params['columns'] as $col) {
                if (isset($params['search']['value']) && $params['search']['value'] != '') {
                    if($this->hasAttribute($col['data'])){
                        $q->orFilterWhere(['like',  $col['data'], $params['search']['value']]);
                    }
                    if($col['data']=='name'){
//                        $q->andFilterWhere(['like',  'tbl_document.name', $params['search']['value']]);
                           $q->andWhere("tbl_document.name like '%".$params['search']['value']."%'");
                    }
                    if($col['data']=='doc'){
                        $d=Documents::find()->where(['like','name',$params['search']['value']])->select(['category_id'])->all();
                        $q->andWhere(' `' . self::tableName() . "`.id IN ('" . join("','", ArrayHelper::getColumn($d, 'category_id')) . "') ");
//                        $q->andFilterWhere(['like',  'description', $col['search']['value']]);
                    }
                }
            }
        }

        if (isset($params['order'])) {
            $sort = [];
            foreach ($params['order'] as $item){
                $arr = isset($item['dir']) ? $item['dir'] : 'asc';
                $col = isset($item['column']) && isset($params['columns'][$item['column']]) ? $params['columns'][$item['column']]['data'] : '0';
//                if ((new self())->hasAttribute($col)) {
//                    $sort = self::tableName() . '.' . $col . ' ' . $arr;
//                }
                if ($col == 'name') {
                    $sort =  'tbl_document.name ' . $arr;
                }
                if($col=='dateCreate'){
                    $sort='tbl_document.create_at '. $arr;
                }
            }
            $q->orderBy($sort);
        }
    
       return DataTableAjax::renderAjax($q, ['allData' => $total]);
    }

    /**
     * @return void
     */
    public function getNama(){
        $out='';
        if($this->tblDocuments==[]){
            return '';
        }
        foreach ($this->tblDocuments as $doc){
            $out.=$doc->name.'<br>';
        }
        return $out;
    }

    /**
     * @return void
     */
    public function getUserCreate(){
        $out='';
        if($this->tblDocuments==[]){
            return '';
        }
        foreach ($this->tblDocuments as $doc){
            $out.=$doc->user_create.'<br>';
        }
        return $out;
    }

    /**
     * @return string
     */
    public function getCategoryName(){
        return $this->description;
    }
    public function getDoc(){
           $out=Html::tag('thead',Html::tag('tr',
                Html::tag('td','').
                Html::tag('td','Dibuat',['width'=>'15%']).
                Html::tag('td','Tanggal',['width'=>'15%'])
            )
        ).'<tbody>';
        if($this->tblDocuments==[]){
           return '';
        }
        foreach ($this->document as $doc){
            $out.=Html::tag('tr',
                Html::tag('td',Html::tag('a',
                    Html::tag('h6', $doc->name,['class'=>'product-name mb-2']),['href'=>Url::to(['/document/default/view-pdf','id'=>$doc->id]),'data-action'=>'view'])).
                Html::tag('td',$doc->user_create).
                Html::tag('td',date('d-m-Y',strtotime($doc->create_at)))
            );
        }
        return
            Html::tag('table',$out.'</tbody>',['class'=>'table','width'=>'100%']);
    }

    public $_userArray;
    public function getUserArray(){
        if($this->_userArray==null){
            $this->_userArray=explode(',',$this->user_id);
        }
        return $this->_userArray;
    }

    public function setUserArray($arr){
        if(is_array($arr)){
            $this->user_id=join(',',$arr);
        }
        $this->_userArray=$arr;
    }

    public function getListUser(){
        return ArrayHelper::map(Users::find()->all(),'id_user','username');
    }
  

   
    public function renderJenis($new){
        if($new=='ISO 17065'){
            $this->type=1;
        }
        if($new=='internal'){
            $this->type=3;
        }
        if($new=='eksternal'){
            $this->type=2;
        }
    }

    public function getReq($type){
        if($type==1){
            return 'ISO 17065';
        }
        if($type==2){
            return 'eksternal';
        }
        return 'internal';
    }
}

modules/document/controllers/DefaultController.php
<?php
/**
 * DefaultController.php
 * Created By
 * feri_
 * 23/01/2023
 */

namespace app\modules\document\controllers;
use Yii;
use yii\helpers\ArrayHelper;
use yii\web\Response;
use app\modules\document\models\FormDocument;
use app\modules\document\models\Categories;
use app\modules\document\models\FormCategory;
use yii\helpers\Url;
use yii\web\NotFoundHttpException;
class DefaultController extends \yii\web\Controller
{
    public function beforeAction($action)
    {
        if (in_array($action->id, ['create-category','delete','delete-document'])) {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action);
    }

    public function actionListCategory(){
        $g=isset($_GET['q'])?$_GET['q']:'';
        $type=$_GET['type'];
        $q=Categories::find()->where("type='$type'");
        $q->andWhere(['like','description',$g]);
        $q->select(['id','description','level']);
        $out=[];
        foreach ($q->all() as $rec){
            $out[]=[
                'id'=>$rec->id,
                'text'=>$rec->description,
                'level'=>$rec->level,
            ];
        }
        if($q->all()==null){
            $out[]=[
                'id'=>0,
                'text'=>$g,
                'level'=>0
            ];
        }
        Yii::$app->response->format=Response::FORMAT_JSON;
        return [
            'results'=>$out
        ];
    }
    public function actionIndex(){
        $model=new FormCategory();
        $param=Yii::$app->request->queryParams;
        // $param['jenis']=$param['jenis'];
        if(Yii::$app->request->isAjax){
            return $model->renderData($param);
        }
        return $this->render('_index',['model'=>$model]);
    }

    public function actionNew(){
        $request=Yii::$app->request->queryParams;
        $model=new FormCategory();
        $model->renderJenis($request['jenis']);
        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['/document/default','jenis'=>$request['jenis']]);
        }
        // $model->level=$_GET['level'];
        // if(Yii::$app->request->isAjax){
        //     Yii::$app->response->format=Response::FORMAT_JSON;
        //     if($model->load(Yii::$app->request->post())){
        //        return [
        //            'status'=>$model->save()?'success':'error'
        //        ];
        //     }
        //     return $this->renderAjax('form',['model'=>$model]);
        // }
        return $this->render('create',['model'=>$model]);
    }

    public function actionEdit($id){
        $model=$this->findModel($id);
        $request=Yii::$app->request->queryParams;
        if($model->load(Yii::$app->request->post()) && $model->save()){
            return $this->redirect(['/document/default','jenis'=>$request['jenis']]);
        }
        return $this->render('edit',['model'=>$model]);
    }

    public function actionDelete($id){
        $model=$this->findModel($id);
        Yii::$app->response->format=Response::FORMAT_JSON;
        return [
            'status'=>$model->delete()?'success':'error',
            'data'=>array_merge($model->toArray(),[
                'actions'=>$model->actions,
            ])
            ];
    }
    public function actionDeleteDocument($id){
        $model=FormDocument::find()->where(['id'=>$id])->one();
        Yii::$app->response->format=Response::FORMAT_JSON;
        return [
            'status'=>$model->delete()?'success':'error',
            'data'=>array_merge($model->toArray(),[
                'actions'=>$model->actions,
            ])
            ];
    }
    public function actionView($id){
        $model=new FormDocument();
        $request=Yii::$app->request->queryParams;
        $request['category_id']=$id;
        if(Yii::$app->request->isAjax){
           return $model->renderData($request);
        }
        return $this->render('view',['model'=>$model]);
    }

    public function actionViewPdf($id){
        $userLevel=Yii::$app->user->identity->level;
        $model=FormDocument::find()->where(['id'=>$id])->one();
        $level=$model->level;
        $img=getimagesize($model->getDirBerkas().'/'.$model->file_name);
        Yii::$app->response->format=Response::FORMAT_JSON;
        if($userLevel==0){
            if($level==0 || $level==4){
                return [
                    'form'=>$this->renderAjax('img',['model'=>$model]),
                    'file'=>$model->getUrlFile()
                ];
            }
            return [
                'form'=>$this->renderAjax($img==null?'pdf1':'img',['model'=>$model]),
                'file'=>$model->getUrlFile()
            ];
        }
        return [
            'form'=>$this->renderAjax('img',['model'=>$model]),
            'file'=>$model->getUrlFile()
        ];
//        return $this->renderAjax('pdf1',['model'=>$model]);
    }

    public function actionCreateCategory(){
        $model=new Categories();
        $post=Yii::$app->request->post();
        if(isset($post['description']) && $post['description']!=''){
            $model->description=$post['description'];
            Yii::$app->response->format=Response::FORMAT_JSON;
            if($model->save()){
                return [
                    'id'=>$model->id,
                    'text'=>$model->description
                ];
            }
            return [
                'id'=>0,
                'text'=>'text'
            ];
        }
    }
    public function actionDetails(){
        $id=$_GET['id'];
        $model=new FormDocument();
        Yii::$app->response->format=Response::FORMAT_JSON;
        return $model->renderDetails($id);
    }

    protected function findModel($id)
    {
        if (($model = FormCategory::findOne(['id' => $id])) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    public function actionEditDocument($id){
        $post=Yii::$app->request->post();
        $model=FormDocument::find()->where(['id'=>$id])->one();
        // if($model!=null){
            if(isset($post['tahun'])){
                $model->tahun=$post['tahun'];
            }
            if(isset($post['rev'])){
                $model->rev=$post['rev'];
            }
            if(isset($post['level'])){
                $model->level=$post['level'];
            }
            Yii::$app->response->format=Response::FORMAT_JSON;
             return [
                'status'=>$model->save()?'success':'error',
                'data'=>array_merge($model->toArray(),[
                    'tahunText'=>$model->tahunText,
                    'actions'=>$model->actions,
                    'levelText'=>$model->levelText,
                    'revText'=>$model->revText,
                ])
            ];   
           
        // }
    }

    public function actionEditJenis($id){
        $model=Categories::find()->where(['id'=>$id])->one();
        if($model->load(Yii::$app->request->post())){
            if(Yii::$app->request->isAjax){
                Yii::$app->response->format=Response::FORMAT_JSON;
                return [
                    'status'=>$model->save()?'success':'error',
                    'message'=>'save',
                    'data'=>array_merge($model->toArray(),
                    [
                        'detail'=>$model->detail,
                        'actions'=>$model->actions
                    ])
                ]; 
            }
            if($model->save()){
                if($model->type==1){
                    return $this->redirect(Url::to(['/document/internal']));
                }
                return $this->redirect(Url::to(['/document/eksternal']));
            }
            
        }
        return $this->render('edit_jenis',['model'=>$model]);
    }
}

modules/document/views/default/_form.php
<?php
use yii\bootstrap5\ActiveForm;
use app\synui\ThemeAssets;
$assets = ThemeAssets::register($this);
?>
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2.min.css" rel="stylesheet" />
<script src="<?= $assets->baseUrl ?>/plugins/select2/js/select2.min.js"></script>



<?php 
    
    $form = ActiveForm::begin([
    'id' => 'form-jenis',
//        'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{error}",
        'labelOptions' => ['class' => 'form-label'],
        'inputOptions' => ['class' => 'form-control'],
//        'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
    ],
    'options' => [
        'class'=>'row g-3',
        'enctype' => 'multipart/form-data',
    ]
]); ?>

<div class="col-md-12">
    <?= $form->field($model,'description')->textInput(['maxlength'=>true]) ?>
</div>
<div class="col-md-2">
        <?= $form->field($model,'level')->textInput(['type'=>'number','value'=>1]) ?>
    </div>
<div class="col-md-10">
    <?= $form->field($model,'userArray')->dropdownList($model->listUser,['class'=>'select2ajx','multiple'=>'multiple'])->label('User') ?>
</div>
<div class="col-md-12">
    <?= $form->field($model,'fileUpload[]')->fileInput(['multiple' => true]) ?>
</div>
<div class="col-md-12">
    <button type="submit" id="submit" class="btn btn-primary">Submit</button>
</div>
<?php ActiveForm::end(); ?> 
<script>
    $(function(){
        $('.select2ajx').select2();
    })
</script>

modules/document/views/default/create.php
<?php
/**
 * create.php
 * Created By
 * feri_
 * 23/01/2023
 */
use app\synui\ThemeAssets;
$assets=ThemeAssets::register($this);
$req=Yii::$app->request->queryParams;
?>
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2.min.css" rel="stylesheet" />
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2-bootstrap4.css" rel="stylesheet" />
<script src="<?= $assets->baseUrl ?>/plugins/select2/js/select2.min.js"></script>
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">Document</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="book-outline"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">New Dokumen <?= ' '.$req['jenis'] ?></li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-xl-12 mx-auto">
        <h6 class="mb-0 text-uppercase">New Document</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="p-4 border rounded">
                    <?= $this->render('_form',['model'=>$model]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

modules/document/views/default/edit.php
<?php
/**
 * create.php
 * Created By
 * feri_
 * 23/01/2023
 */
use app\synui\ThemeAssets;
$assets=ThemeAssets::register($this);
$req=Yii::$app->request->queryParams;
?>
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2.min.css" rel="stylesheet" />
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2-bootstrap4.css" rel="stylesheet" />
<script src="<?= $assets->baseUrl ?>/plugins/select2/js/select2.min.js"></script>
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">Document</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="book-outline"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Edit Dokumen <?= ' '.$req['jenis'] ?></li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-xl-12 mx-auto">
        <h6 class="mb-0 text-uppercase">New Document</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="p-4 border rounded">
                    <?= $this->render('_form',['model'=>$model]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

modules/document/views/default/edit_jenis.php
<?php
use yii\bootstrap5\ActiveForm;
use app\synui\ThemeAssets;
$assets = ThemeAssets::register($this);
?>
<link href="<?= $assets->baseUrl ?>/plugins/select2/css/select2.min.css" rel="stylesheet" />
<script src="<?= $assets->baseUrl ?>/plugins/select2/js/select2.min.js"></script>



<?php 
    
    $form = ActiveForm::begin([
    'id' => 'form-jenis',
//        'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{error}",
        'labelOptions' => ['class' => 'form-label'],
        'inputOptions' => ['class' => 'form-control'],
//        'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
    ],
    'options' => [
        'class'=>'row g-3',
    ]
]); ?>

<div class="col-md-12">
    <?= $form->field($model,'description')->textInput(['max']) ?>
</div>
<div class="col-md-12">
    <?= $form->field($model,'userArray')->dropdownList($model->listUser,['class'=>'select2ajx','multiple'=>'multiple'])->label('User') ?>
</div>
<div class="col-md-12">
    <button type="submit" id="submit" class="btn btn-primary">Submit</button>
</div>
<?php ActiveForm::end(); ?> 
<script>
    $(function(){
        $('.select2ajx').select2();
    })
</script>

modules/document/views/default/form.php
<?php
/**
 * form.php
 * Created By
 * feri_
 * 23/01/2023
 */
use yii\helpers\Url;
use yii\bootstrap5\ActiveForm;
$csrf=Yii::$app->request->csrfParam;
$token= Yii::$app->request->getCsrfToken();
?>
<?php $form = ActiveForm::begin([
    'id' => 'document-form',
//        'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{error}",
        'labelOptions' => ['class' => 'form-label'],
        'inputOptions' => ['class' => 'form-control'],
//        'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
    ],
    'options' => [
        'class'=>'row g-3',
        'enctype' => 'multipart/form-data'
    ]
]); ?>
    <div class="col-md-3">
        <?= $form->field($model,'category_id')->dropDownList($model->category_id==null?[]:[$model->category_id=>$model->description],[
            'data-url'=>Url::to(['/document/default/list-category','type'=>1]),'class'=>'select2'])->label('Jenis') ?>
        <?= $form->field($model,'name')->hiddenInput()->label(false) ?>
    </div>
    <div class="col-md-2">
        <?= $form->field($model,'level')->textInput(['type'=>'number','value'=>1]) ?>
    </div>
    <div class="col-md-2">
        <?= $form->field($model,'rev')->textInput(['type'=>'number','value'=>0])->label('Revisi') ?>
    </div>

    <div class="col-md-2">
        <?= $form->field($model,'tahun')->textInput() ?>
    </div>


    <div class="col-md-12">
        <?= $form->field($model,'fileUpload')->fileInput() ?>
    </div>

    <div class="col-12">
        <button class="btn btn-primary" type="submit">Submit</button>
    </div>
<?php ActiveForm::end(); ?>

modules/document/views/default/img.php
<?php
/**
 * img.php
 * Created By
 * feri_
 * 05/02/2023
 */
?>
<div class="row">

 
    <object data="<?=$model->urlFile.'#toolbar=0&navpanes=0&scrollbar=0'?>" type="application/pdf" width="100%" height="850px">
    </iframe>
</div>

modules/document/views/default/index.php
<?php
/**
 * index.php
 * Created By
 * feri_
 * 23/01/2023
 */
use app\synui\ThemeAssets;
use yii\helpers\Url;
use yii\bootstrap5\Html;
$assets=ThemeAssets::register($this);
$ajax=Url::to();
?>
<link href="<?= $assets->baseUrl ?>/plugins/datatable/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
<link href="<?= $assets->baseUrl ?>/plugins/sweetalert2/css/sweetalert2.min.css" rel="stylesheet" />

<script src="<?= $assets->baseUrl ?>/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="<?= $assets->baseUrl ?>/plugins/datatable/js/dataTables.bootstrap5.min.js"></script>
<script src="<?= $assets->baseUrl ?>/plugins/sweetalert2/js/sweetalert2.all.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf.js"></script>
<!--start breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">Document</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="book-outline"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">List Document</li>
            </ol>
        </nav>
    </div>
    <div class="ms-auto">
        <div class="btn-group">
            <?=Html::tag('a','New',['href'=>Url::to(['/document/default/new']),'class'=>'btn btn-outline-primary']) ?>
        </div>
    </div>
</div>
<!--end breadcrumb-->
<h6 class="mb-0 text-uppercase">List Document</h6>
<hr/>
<div class="card radius-10">
    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>Action</th>
                    <th>Jenis Document</th>
                    <th>Document</th>
                    <th>Dibuat Oleh</th>
                    <th>Tanggal Upload</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>
<!-- Modal -->
<div class="modal fade" tabindex="-1" id="mdl">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<script>
    $(function(){
        let mv=$('#mdl');
        let groupColumn = 1;
        let table=$('#example').DataTable({
            "orderCellsTop": true,
            "scrollX": true,
            "scrollY": "400px",
            "processing": true,
            "serverSide": true,

            "columnDefs": [
                { "visible": false, "targets": groupColumn }
            ],
            "ajax":{
                "url":"<?php $ajax ?>",
                "data":function(d){
                    d.detail=true;
                    return d
                }
            },
            "columns":[
                {"data":"actions","orderable":false,"width":"10%"},
                {"data":"categoryName","orderable":true},
                {"data":"name","orderable":true},
                {"data":"user_create","orderable":true,"width":"15%"},
                {"data":"dateCreate","orderable":true,"width":"15%"}
            ],
            "order": [[ groupColumn, 'asc' ]],
            "displayLength": 25,
            "drawCallback": function ( settings ) {
                var api = this.api();
                var rows = api.rows( {page:'current'} ).nodes();
                var last=null;
                api.column(groupColumn, {page:'current'} ).data().each( function ( group, i ) {
                    if ( last !== group ) {
                        $(rows).eq( i ).before(
                            '<tr class="group"><td colspan="4">'+group+'</td></tr>'
                        );
                        last = group;
                    }
                } );
            },
        });
        $('body').delegate('[data-action=view]','click',function (e){
            e.preventDefault();
            mv.modal('show');
            $.ajax({
                method:'GET',
                url:$(this).attr('href'),
                beforeSend:function (){
                    mv.find('.modal-body').html('<p> Please  wait</p>');
                },
                success:function (res){
                    mv.find('.modal-footer').html('<a href="#" class="btn btn-primary" target="_blank">Unduh File</a>')
                    mv.find('.modal-body').html(res);
                },
                error:function (res){
                    mv.hide();
                }
            })
        })
        $('body').delegate('[data-action=delete]','click',function (e){
            e.preventDefault();
            let elm=$(this);
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method:'POST',
                        url:elm.attr('href'),
                        success:function (res){
                            Swal.fire(
                                'Deleted!',
                                'Your file has been deleted.',
                                'success'
                            )
                            table.ajax.reload();
                        },
                        error:function (res,xr){
                            Swal.fire(
                                'Not Deleted!',
                                'Your file.',
                                'error'
                            )
                        }
                    })
                }
            })
        })
    })

</script>

modules/document/views/default/pdf1.php
<?php

use yii\helpers\Html;
use yii\helpers\Url;

//app\modules\mutu\assets\MutuAssets::register($this);

// Yii::$app->clientScript->registerCoreScript('jquery.ui');
// $this->registerJsFile('@app/modules/invoice/assets/file.js');
?>


<script>
window.onload = function() {
    document.addEventListener("contextmenu", function(e){
        e.preventDefault();
        }, false);
}

$(document).contextmenu(function() { return false;});
url = "<?= $model->urlFile; ?>";
var thePdf = null;
var scale = 1.7;

$(document).ready(function () {
    pdfjsLib.getDocument(url).promise.then(function(pdf) {
        thePdf = pdf;
        viewer = document.getElementById('pdf-viewer');

        for(page = 1; page <= pdf.numPages; page++) {
            canvas = document.createElement("canvas");
            canvas.className = 'pdf-page-canvas';
            viewer.appendChild(canvas);
            renderPage(page, canvas);
        }
    });
    function renderPage(pageNumber, canvas) {
        thePdf.getPage(pageNumber).then(function(page) {
            viewport = page.getViewport(scale);
            canvas.height = viewport.height;
            canvas.width = viewport.width;
            page.render({canvasContext: canvas.getContext('2d'), viewport: viewport});
        });
    }
})


</script>
    </head>
    <body>
        <div class="left" id="pdf-viewer"> </div>
    </body>
</html>