modules/user/models/User.php
<?php
/**
 * User.php
 * Created By
 * feri_
 * 27/01/2023
 */

namespace app\modules\user\models;
use app\component\DataTableAjax;
use Yii;
use yii\bootstrap5\Html;
use yii\helpers\Url;

class User extends \app\modelsDB\Users
{
    public function rules()
    {
        return array_merge(parent::rules(),[
            [['username','password_hash'], 'required'],
            [['username'],'unique'],
        ]);
        // TODO: Change the autogenerated stub
    }
    public function attributeLabels()
    {
        return array_merge(parent::attributeLabels(),[
            'password_hash'=>'Password'
        ]); // TODO: Change the autogenerated stub
    }

    public function save($runValidation = true, $attributeNames = null)
    {

        if(parent::save($runValidation, $attributeNames)){
            return true;
        } // TODO: Change the autogenerated stub\
    }

    public function beforeSave($insert)
    {
        if(parent::beforeSave($insert)){
            // if($this->isNewRecord){
                $this->password_hash=Yii::$app->security->generatePasswordHash($this->password_hash);
            // }
            return true;
        }
        return false;
            // TODO: Change the autogenerated stub
    }

    public function getActions(){
        return Html::tag('div',
            Html::tag('div',
                Html::tag('a','edit',['href'=>Url::toRoute(['/user/default/edit','id'=>$this->id_user]),'class'=>'btn btn-sm btn-outline-primary']).
                Html::tag('a','delete',['href'=>Url::toRoute(['/user/default/delete','id'=>$this->id_user]),'class'=>'btn btn-sm btn-outline-danger','data-action'=>'delete'])
//                Html::tag('a','view',['href'=>Url::toRoute(['/document/default/view-pdf','id'=>$this->id]), 'class'=>'btn btn-sm btn-outline-primary','data-action'=>'view'])
                ,['class'=>'btn-group']),
            ['class'=>'col']);

    }
    public function renderData($params){
        $q=self::find();
        $total=$q->count('id_user');
        return DataTableAjax::renderAjax($q, ['allData' => $total]);
    }

    public function getStatus(){
        if($this->level==2){
            return 'Admin';
        }
        if($this->level==1){
            return 'Manager';
        }
        return 'User';
        // return $this->level==2?'Admin':$this->level==1?'Manager':'User';

    }

    public function getListLevel(){
        return [
            0=>'User',
            1=>'Manager',
            2=>'Admin'
        ];
    }
}

modules/user/controllers/DefaultController.php
<?php
/**
 * DefaultController.php
 * Created By
 * feri_
 * 27/01/2023
 */

namespace app\modules\user\controllers;
use app\modules\user\models\User;
use Yii;
use yii\helpers\Url;
class DefaultController extends \yii\web\Controller
{
    public function actionIndex(){
        $model=new User();
        $param=Yii::$app->request->queryParams;
        if(Yii::$app->request->isAjax){
            return $model->renderData($param);
        }
        return $this->render('index',['model'=>$model]);
    }
    public function actionCreate(){
        $model=new User();
        $post=Yii::$app->request->post();
        if($model->load($post)){
            if($model->save()){
                return $this->redirect(Url::to(['/user/default']));
            }
        }
        return $this->render('create',['model'=>$model]);
    }
    public function actionEdit($id){
        $model= User::findOne(['id_user'=>$id]);
        $post=Yii::$app->request->post();
        if($model->load($post)){
            if($model->save()){
                return $this->redirect(Url::to(['/user/default']));
            }
        }
        return $this->render('edit',['model'=>$model]);
    }

}

modules/user/views/default/create.php
<?php
/**
 * create.php
 * Created By
 * feri_
 * 23/01/2023
 */
?>
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">User</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="person-circle-sharp"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">New User</li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-xl-8 mx-auto">
        <h6 class="mb-0 text-uppercase">Document</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="p-3 border rounded">
                    <?= $this->render('form',['model'=>$model]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

modules/user/views/default/edit.php
<?php
/**
 * create.php
 * Created By
 * feri_
 * 23/01/2023
 */
?>
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">User</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="person-circle-sharp"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">Edit User</li>
            </ol>
        </nav>
    </div>
</div>
<div class="row">
    <div class="col-xl-8 mx-auto">
        <h6 class="mb-0 text-uppercase">Document</h6>
        <hr/>
        <div class="card">
            <div class="card-body">
                <div class="p-3 border rounded">
                    <?= $this->render('form',['model'=>$model]) ?>
                </div>
            </div>
        </div>
    </div>
</div>

modules/user/views/default/form.php
<?php
/**
 * form.php
 * Created By
 * feri_
 * 23/01/2023
 */
use yii\helpers\Url;
use yii\bootstrap5\ActiveForm;
$csrf=Yii::$app->request->csrfParam;
$token= Yii::$app->request->getCsrfToken();
$readonly=true;
?>
<?php $form = ActiveForm::begin([
    'id' => 'user-form',
//        'layout' => 'horizontal',
    'fieldConfig' => [
        'template' => "{label}\n{input}\n{error}",
        'labelOptions' => ['class' => 'form-label'],
        'inputOptions' => ['class' => 'form-control'],
//        'errorOptions' => ['class' => 'col-lg-7 invalid-feedback'],
    ],
    'options' => [
        'class'=>'row g-3',

    ]
]); ?>
<div class="col-12">
    <?= $form->field($model,'username')->textInput(['maxlength'=>true]) ?>
</div>
<div class="col-12">
   <?= $form->field($model,'password_hash')->passwordInput() ?>
</div>
<div class="col-12">
    <?= $form->field($model,'level')->dropDownList($model->listLevel)?>
</div>

<div class="col-12">
    <button class="btn btn-primary" type="submit">Submit</button>
</div>
<?php ActiveForm::end(); ?>
<script>
    $(function(){
        "use strict";
        $('.select2').select2({
            theme: 'bootstrap4',
             width:  '100%',
            placeholder: $(this).data('placeholder'),
            allowClear: Boolean($(this).data('allow-clear')),
            ajax: {
                url: function (a) {
                    return this.attr('data-url');
                },
                data: function (params) {
                    let el = this;
                    let query = {
                        q: params.term,
                        // param: {
                        //     // col: el.attr('data-depend'),
                        //     // fromcol: el.attr('data-depend-from'),
                        //     filter: form.find('#' + el.attr('data-depend-id')).val(),
                        // }
                    };
                    return query;
                },
                processResults: function (data) {
                    return {
                        results: data.results
                    };
                }
            }
        })
        $('.select2').on('select2:select',function (e){
            let data=e.params.data
            let elm=$(this);
            if(data.id==0){

               // console.log(elm.attr('data-name'))
                $.ajax({
                    url:elm.attr('data-action'),
                    method:'POST',
                    data:{description:data.text},
                }).then(function (data) {
                    console.log(data)
                    // create the option and append to Select2
                    let option = new Option(data.text, data.id, true, true);
                    elm.append(option).trigger('change')
                    // manually trigger the `select2:select` event
                    elm.trigger({
                        type: 'select2:select',
                        params: {
                            data: data
                        }
                    })
                });
            }

        })
    })
</script>

modules/user/views/default/index.php
<?php
/**
 * index.php
 * Created By
 * feri_
 * 27/01/2023
 */
use app\synui\ThemeAssets;
use yii\helpers\Url;
use yii\bootstrap5\Html;
$assets=ThemeAssets::register($this);
$ajax=Url::to();
?>
<link href="<?= $assets->baseUrl ?>/plugins/datatable/css/dataTables.bootstrap5.min.css" rel="stylesheet" />
<link href="<?= $assets->baseUrl ?>/plugins/sweetalert2/css/sweetalert2.min.css" rel="stylesheet" />

<script src="<?= $assets->baseUrl ?>/plugins/datatable/js/jquery.dataTables.min.js"></script>
<script src="<?= $assets->baseUrl ?>/plugins/datatable/js/dataTables.bootstrap5.min.js"></script>
<script src="<?= $assets->baseUrl ?>/plugins/sweetalert2/js/sweetalert2.all.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.3.200/pdf.js"></script>
<!--start breadcrumb-->
<div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
    <div class="breadcrumb-title pe-3">Users</div>
    <div class="ps-3">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb mb-0 p-0 align-items-center">
                <li class="breadcrumb-item"><a href="javascript:;"><ion-icon name="person-circle-sharp"></ion-icon></a>
                </li>
                <li class="breadcrumb-item active" aria-current="page">List User</li>
            </ol>
        </nav>
    </div>
    <div class="ms-auto">
        <div class="btn-group">
            <?=Html::tag('a','New',['href'=>Url::to(['/user/default/create']),'class'=>'btn btn-outline-primary']) ?>
        </div>
    </div>
</div>
<!--end breadcrumb-->
<h6 class="mb-0 text-uppercase">List Document</h6>
<hr/>
<div class="card radius-10">
    <div class="card-body">
        <div class="table-responsive">
            <table id="example" class="table table-striped table-bordered" style="width:100%">
                <thead>
                <tr>
                    <th>Action</th>
                    <th>User Name</th>
                    <th>Level</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
</div>

<script>
    $(function(){
        let mv=$('#mdl');
        let groupColumn = 1;
        let table=$('#example').DataTable({
            "orderCellsTop": true,
            "scrollX": true,
            "scrollY": "400px",
            "processing": true,
            "serverSide": true,
            "ajax":{
                "url":"<?php $ajax ?>",
                "data":function(d){
                    d.detail=true;
                    return d
                }
            },
            "columns":[
                {"data":"actions","orderable":false,"width":"10%"},
                {"data":"username","orderable":true},
                {"data":"status","orderable":true,"width":"15%"}
            ],
            "order": [[ groupColumn, 'asc' ]],
            "displayLength": 25,
            // "drawCallback": function ( settings ) {
            //     var api = this.api();
            //     var rows = api.rows( {page:'current'} ).nodes();
            //     var last=null;
            //     api.column(groupColumn, {page:'current'} ).data().each( function ( group, i ) {
            //         if ( last !== group ) {
            //             $(rows).eq( i ).before(
            //                 '<tr class="group"><td colspan="4">'+group+'</td></tr>'
            //             );
            //             last = group;
            //         }
            //     } );
            // },
        });
        $('body').delegate('[data-action=view]','click',function (e){
            e.preventDefault();
            mv.modal('show');
            $.ajax({
                method:'GET',
                url:$(this).attr('href'),
                beforeSend:function (){
                    mv.find('.modal-body').html('<p> Please  wait</p>');
                },
                success:function (res){
                    mv.find('.modal-body').html(res);
                },
                error:function (res){
                    mv.hide();
                }
            })
        })
        $('body').delegate('[data-action=delete]','click',function (e){
            e.preventDefault();
            let elm=$(this);
            Swal.fire({
                title: 'Are you sure?',
                text: "You won't be able to revert this!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Yes, delete it!'
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        method:'POST',
                        url:elm.attr('href'),
                        success:function (res){
                            Swal.fire(
                                'Deleted!',
                                'Your file has been deleted.',
                                'success'
                            )
                            table.ajax.reload();
                        },
                        error:function (res,xr){
                            Swal.fire(
                                'Not Deleted!',
                                'Your file.',
                                'error'
                            )
                        }
                    })
                }
            })
        })
    })

</script>